// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Id int `path:"id"`
}

type Response struct {
	Message string `json:"message"`
}

type UserGetRequest struct {
	Name string `json:"name"`
}

type UserGetResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type PingRequest struct {
}

type PingResponse struct {
	Message string `json:"message"`
}

type SigninRequest struct {
	Email    string    `json:"email"`
	Password string `json:"password"`
}

type SigninResponse struct {
	Message   string `json:"message"`
	Nama      string `json:"name"`
	Email     string `json:"email"`
	Token     string `json:"token"`
	CreatedAt string `json:"created_at"`
}

type SignupRequest struct {
	Email string `json:"email"`
}

type SignupResponse struct {
	Message string `json:"message"`
}
